---
- name: Apply the Zcash Gitian builder role.
  become: yes
  hosts: localhost:zcash-build
  vars:
    zcash_git_repo_url: https://github.com/ZclassicDev/zclassic
    zcash_version: master
    gpg_key_name: ''
    git_name: ''
    git_email: ''
    gpg_key_id: '' # optional
    ssh_key_name: '' # optional
  roles:
    - role: common
      tags: common
    - role: gitian
      tags: gitian
